version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      args:
        - BACKEND_URL=http://localhost:5001
    ports:
      - 4200:80
    mem_limit: 64m
    cpus: 0.1
    networks:
      - development

  backend:
    build: ./backend
    environment:
      - CorsSettings_Origins=http://localhost:4200
      - JwtSettings__Key=s0m3S3ecsfdsd72384%^%@#%r3Tkey
      - JwtSettings__Issuer=DevToClone
      - JwtSettings__Audience=DevToCloneAudience
      - JwtSettings__DurationInMinutes=360
      - ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=DevToCloneDb;User=SA;Password=Admin@123
      - StorageSettings__BucketName=${AWS_STORAGE_BUCKET}
      - AWS__Profile=default
      - AWS__Region=ap-southeast-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    mem_limit: 64m
    cpus: 0.1
    ports:
      - 5001:80
    depends_on:
      - mssql
    networks:
      - development

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin@123
    volumes:
      - mssql-data
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ""$$SA_PASSWORD"" -Q "SELECT 1" || exit 1
      timeout: 45s
      interval: 10s
      retries: 10
    mem_limit: 1Gb
    cpus: 0.2
    ports:
      - 1433:1433
    networks:
      - development

networks:
  development:
    driver: bridge

volumes:
  mssql-data:
    driver: local
